CREATE TABLE public.dnse_orders (
    id BIGINT PRIMARY KEY,
    side TEXT NOT NULL,
    account_no TEXT NOT NULL,
    investor_id TEXT NOT NULL,
    symbol TEXT NOT NULL,
    price NUMERIC,
    quantity NUMERIC,
    order_type TEXT,
    order_status TEXT,
    fill_quantity NUMERIC,
    last_quantity NUMERIC,
    last_price NUMERIC,
    average_price NUMERIC(18, 4),
    trans_date TIMESTAMP WITH TIME ZONE,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    modified_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    tax_rate NUMERIC,
    fee_rate NUMERIC,
    leave_quantity NUMERIC,
    canceled_quantity NUMERIC,
    price_secure NUMERIC,
    custody TEXT,
    channel TEXT,
    loan_package_id BIGINT,
    initial_rate NUMERIC,
    error TEXT
);
